# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: BIO
    url: /
    weight: 10
  - name: PUBLICATIONS
    url: /#papers
    weight: 11
  - name: TALKS
    url: /#talks
    weight: 30
  - name: NEWS
    url: /#news
    weight: 12
  - name: EXPERIENCE
    url: experience/
    weight: 13
  - name: PROJECTS
    url: projects/
    weight: 20
  - name: BLOGS
    url: blogs/
    weight: 40
  #- name: Teaching
  #  url: teaching/
  #  weight: 40
